name: Deploy to cloudtype
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: gayeon7877/pack-it
          stage: main
          yaml: |
            name: pack-it
            app: node@18
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: DB_HOST
                  value: ${{ secrets_DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets_DB_PORT }}
                - name: DB_USER
                  value: ${{ secrets_DB_USER }}
                - name: DB_PASSWORD
                  value: ${{ secrets_DB_PASSWORD }}
              ports: 3000
              install: npm ci
              build: npm run build
              start: npm run start:dev
              healthz: /
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
