name: Node.js Dev CI/CD

on:
  pull_request:      # pull request -> merge 가 되었을 때 돌아라
    type: [ closed ]
  workflow_despatch: # 수동 실행도 가능하도록 함

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3   # build 할 코드를 가져옴 (코드 check out)

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install node_modules
        run: npm ci   # install dependencies

      - run: npm run build --if-present
      # Beanstalk 배포
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_ACTION_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_ACTION_SECRET_ACCESS_KEY}}
          application_name: beanstalkpractice
          environment_name: Beanstalkpractice-env-1
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}  # version_label은 이전에 배포한 label과 중복되면 안됨!
          use_existing_version_if_available: true
          region: ap-northeast-2
          deployment_package: dist/deploy.zip
          wait_for_deployment: false  # 바로 Beanstalk으로 넘어갈 수 있도록 함

      # 그냥 다 했다고 출력하기
      - name: Deployed!
        run: echo App deployed to ELB